---
language:
  - generic
os: linux
dist: trusty
sudo: required
env:
  global:
    - APT_URL=packages.ros.org
    - APT_REPO=ros-shadow-fixed
    - DEB_DISTRIBUTION=trusty
    - DEB_ARCH=amd64
    - BINTRAY_REPOSITORY=furushchev/ros-shadow-fixed
    - BINTRAY_USER=furushchev
before_script:
  - sudo sh -c "echo \"deb http://$APT_URL/$APT_REPO/ubuntu $DEB_DISTRIBUTION main\" > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y python-rosinstall-generator lsb-release sed grep gawk aptitude curl jq
script:
  - ./build.sh
